import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { getOptionsForVote } from "@/utils/getRandomPokemon";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [first, second] = getOptionsForVote();

  const { isLoading, data } = trpc.example.hello.useQuery({
    text: "from tRPC",
  });

  return isLoading ? (
    <div>...loading</div>
  ) : (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col items-center justify-center bg-slate-500">
        <h1 className="m-12 text-center text-2xl text-pink-50">
          Which Pokemon is Rounder?
        </h1>
        {data?.greeting}
        <div className="p-8" />
        <div className="flex max-w-2xl items-center justify-between rounded border  p-8 text-white">
          <div className="h-16 w-16 bg-red-200">{first}</div>
          <div className="p-8">VS</div>
          <div className="h-16 w-16 bg-red-200">{second}</div>
        </div>
      </main>
    </>
  );
};

export default Home;
